#!/bin/bash

python midi_asplode.py $1
adb-foreach uninstall "jonahss.myfirstproject"
adb-foreach install -r 5ratApp/bin/classes/MyFirstProject.apk
#node install-ios.js path/to/app
adb-foreach shell am start -n "jonahss.myfirstproject/.Funtime"
node controller.js
